bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_recipes, name='all_recipes'),
    path('<int:recipe_id>/', views.recipe, name='recipe'),
    path('add/', views.add_recipe, name='add_recipe'),
    path('edit/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('delete/<int:recipe_id>/',
         views.delete_recipe,
         name='delete_recipe'),
    path('vote/<int:pk>/', views.vote, name='vote'),
]

recipes_and_deliveries/urls.py
# Favicon code from https://simpleit.rocks/python/django/django-favicon-adding/

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('recipes/', include('recipes.urls')),
    path('contact/', include('contact.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from products.models import Product

from ckeditor.fields import RichTextField


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('sku',)

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, default="", blank=True)
    sku = models.CharField(max_length=254, default="", blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        self.friendly_name = self.friendly_name.title()
        return self.friendly_name

    def save(self):
        # Credit: https://stackoverflow.com/a/31094863/14773450
        # set name to be friendly name
        self.name = self.friendly_name
        super().save(self)


class Tag(models.Model):

    class Meta:
        verbose_name_plural = 'Tags'
        ordering = ('tagname',)

    tagname = models.CharField(max_length=254)

    def __str__(self):
        self.tagname = self.tagname.capitalize()
        return self.tagname


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipe_posts',
                               default="",
                               blank=True,
                               null=True)
    title = models.CharField(max_length=150)
    intro = models.CharField(max_length=254)
    prep_time = models.CharField(max_length=20)
    cook_time = models.CharField(max_length=20, default="", blank=True)
    total_time = models.CharField(max_length=20, default="", blank=False)
    servings = models.IntegerField()
    category = models.ManyToManyField('Category', blank=True)
    tag = models.ManyToManyField('Tag', blank=True)
    directions = RichTextField(blank=True, null=True)
    image = models.ImageField(null=True, blank=True)
    image_credit = models.CharField(max_length=254, default="", blank=True)
    date = models.DateTimeField(auto_now_add=True)
    date_posted = models.DateTimeField(null=True,
                                       blank=True,
                                       default=timezone.now)
    date_edited = models.DateTimeField(auto_now=True)
    recipe_box = models.OneToOneField(Product, related_name='box',
                                      on_delete=models.SET_NULL,
                                      null=True,
                                      blank=True)
    vote_count = models.IntegerField(default=0)
    votes = models.ManyToManyField(User,
                                   related_name='recipe_post_votes',
                                   blank=True)
    mail_sent = models.BooleanField(default=False, null=True, blank=True)
    discount_code = models.CharField(max_length=6, blank=True, default="")

    def total_votes(self):
        return self.vote_count

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    quantity = models.FloatField(default="", blank=True)
    unit = models.CharField(max_length=15, default="", blank=True)
    name = models.CharField(max_length=150, default="", blank=True)
    preparation = models.CharField(max_length=150, default="", blank=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='ingredients')

    def __str__(self):
        return self.name

    # If quantity is whole number, remove the decimal places
    # Credit: https://stackoverflow.com/a/4566018/14773450
    def get_quantity(self):
        if self.quantity == int(self.quantity):
            self.quantity = int(self.quantity)
        return self.quantity

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, mail_admins
from django.template.loader import render_to_string

from .models import Recipe, Category, Tag
from .forms import (
    RecipeForm, IngredientFormSet, NewCategoriesForm,
    NewTagsForm)
from django.contrib.auth.models import User
from django.conf import settings

from random import shuffle, randrange


def all_recipes(request):
    """ A view to return all recipes """
    recipes = Recipe.objects.all().order_by('-pk')
    authors = None
    categories = None
    tags = None
    sort = None
    direction = None
    query = None

    if request.GET:
        # Sort recipes via the dropdown menu
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'title':
                sortkey = 'lower_title'
                recipes = recipes.annotate(lower_title=Lower('title'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            recipes = recipes.order_by(sortkey)

        # Sort recipes by category
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            recipes = recipes.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        # Sort recipes by tag
        if 'tag' in request.GET:
            tags = request.GET['tag'].split(',')
            recipes = recipes.filter(tag__tagname__in=tags)
            tags = Tag.objects.filter(tagname__in=tags)

        # Sort recipes by author
        if 'author' in request.GET:
            authors = request.GET['author'].split(',')
            recipes = recipes.filter(author_id__username__in=authors)
            authors = User.objects.filter(username__in=authors)

    current_sorting = f'{sort}_{direction}'

    template = 'recipes/all_recipes.html'

    paginator = Paginator(recipes, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'recipes': recipes,
        'search_term': query,
        'current_categories': categories,
        'current_tags': tags,
        'current_sorting': current_sorting,
        'current_authors': authors,
        'page_obj': page_obj,
        'is_paginated': True,
    }
    return render(request, template, context)


def recipe(request, recipe_id):
    """ A view to show an individual recipe and random others in side bar """
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    other_recipes = list(Recipe.objects.exclude(id=recipe.id))
    shuffle(other_recipes)

    votes = get_object_or_404(Recipe, id=recipe.id)
    total_votes = votes.total_votes()
    voted = False
    if votes.votes.filter(id=request.user.id).exists():
        voted = True

    context = {
        'recipe': recipe,
        'other_recipes': other_recipes,
        'total_votes': total_votes,
        'voted': voted,
    }

    return render(request, 'recipes/recipe.html', context)


@login_required
def vote(request, pk):
    """ A view to handle the voting for recipes functionality """
    recipe = get_object_or_404(Recipe, id=request.POST.get('recipe_id'))
    voted = False
    if recipe.votes.filter(id=request.user.id).exists():
        recipe.votes.remove(request.user)
        recipe.vote_count -= 1
        recipe.save()
        voted = False
        messages.success(request, 'Your vote has been removed!')
    else:
        recipe.votes.add(request.user)
        recipe.vote_count += 1
        recipe.save()
        voted = True
        messages.success(request, 'Your vote has been registered!')

        # Send mail at threshold of votes
        mail_sent = recipe.mail_sent
        total_votes = recipe.total_votes()

        if total_votes == 1000:
            if mail_sent is False:
                # Generate discount code
                discount_code = randrange(100000, 1000000, 6)
                # Save discount code to recipe
                recipe.discount_code = discount_code
                recipe.save()
                # Send mail to author
                cust_email = recipe.author.email
                subject = render_to_string(
                    'recipes/congratulation_emails/congrats_email_subject.txt',
                    {'recipe': recipe})
                body = render_to_string(
                    'recipes/congratulation_emails/congrats_email_body.txt',
                    {'recipe': recipe,
                     'contact_email': settings.DEFAULT_FROM_EMAIL})
                # Send mail to admin
                admin_subject = render_to_string(
                    'recipes/congratulation_emails/add_recipe_subject.txt',
                    {'recipe': recipe})
                admin_body = render_to_string(
                    'recipes/congratulation_emails/add_recipe_body.txt',
                    {'recipe': recipe,
                     'contact_email': settings.DEFAULT_FROM_EMAIL})

                send_mail(
                    subject,
                    body,
                    settings.DEFAULT_FROM_EMAIL,
                    [cust_email],
                    fail_silently=True,
                )
                # Ensure mail is sent only once
                recipe.mail_sent = True
                recipe.save()

                mail_admins(
                    admin_subject,
                    admin_body,
                    )

    return HttpResponseRedirect(reverse('recipe', args=[str(pk)]))


@login_required
def add_recipe(request):
    """ A view to handled adding recipes """
    if request.method == 'POST':
        recipe_form = RecipeForm(request.POST, request.FILES)
        new_tag_form = NewTagsForm(request.POST)
        new_category_form = NewCategoriesForm(request.POST)
        formset = IngredientFormSet(request.POST)
        if recipe_form.is_valid():
            author = get_object_or_404(User, id=request.user.id)

            # Check button for adding further recipes
            add_more_recipes = request.POST.getlist('add-more-recipes')

            recipe_form_temp = recipe_form.save(commit=False)

            recipe_form_temp.author = author
            recipe = recipe_form.save()
            formset = IngredientFormSet(request.POST, instance=recipe)
            if formset.is_valid():
                formset.save()

            # Handle new vs existing tags
            no_space_tags = True
            new_tags_form = NewTagsForm(request.POST)
            if new_tags_form.data['tagname']:
                new_tagname = new_tags_form.data['tagname']
                tagname_collection = Tag.objects.all()
                existing_tagname = Tag.objects.filter(tagname=new_tagname)
                if existing_tagname:
                    existing_tagname_id = (
                        tagname_collection.get(id__in=existing_tagname))
                    recipe.tag.add(existing_tagname_id)
                if not existing_tagname:
                    if ' ' not in new_tagname:
                        new_tags_form.is_valid()
                        newtag = new_tags_form.save()
                        recipe.tag.add(newtag)
                        no_space_tags = True
                    else:
                        no_space_tags = False

            # Handle new vs exiting categories
            no_space_cats = True
            new_category_form = NewCategoriesForm(request.POST)
            if new_category_form.data['friendly_name']:
                new_category_name = new_category_form.data['friendly_name']
                category_collection = Category.objects.all()
                existing_category_name = (
                    Category.objects.filter(friendly_name=new_category_name))
                if existing_category_name:
                    existing_category_name_id = (
                        category_collection.get(id__in=existing_category_name))
                    recipe.category.add(existing_category_name_id)
                if not existing_category_name:
                    if ' ' not in new_category_name:
                        new_category_form.is_valid()
                        newcategory = new_category_form.save()
                        recipe.category.add(newcategory)
                        no_space_cats = True
                    else:
                        no_space_cats = False

            if no_space_tags and no_space_cats:
                messages.success(request, 'Successfully added recipe!')
            else:
                messages.warning(request, 'Your recipe was added, but we were not able \
                    to add your tags and/or categories. Please add these one \
                    word at a time!')
                return redirect(reverse('edit_recipe', args=[recipe.id]))

            # Handle redirect according to whether
            # Further Recipes is checked or not
            if add_more_recipes:
                return redirect(reverse('add_recipe'))
            else:
                return redirect(reverse('all_recipes'))
        else:
            messages.error(request, 'Failed to add your post \
                Please ensure the form is valid.')
    else:
        recipe_form = RecipeForm
        formset = IngredientFormSet
        new_category_form = NewCategoriesForm
        new_tag_form = NewTagsForm

    template = 'recipes/add_recipe.html'

    context = {
        'recipe_form': recipe_form,
        'formset': formset,
        'new_tag_form': new_tag_form,
        'new_category_form': new_category_form,
    }

    return render(request, template, context)

recipes/templates/recipes/add_recipe.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'recipes/css/recipes.css' %}">
{% endblock %}

{% block extra_title %}
 | Add a Recipe
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container content mb-3">
    <!-- Page title row -->
    <div class="row">
        <div class="col-12 mt-3">
            <h2 class="font-weight-bold">Add A New Recipe</h2>
            <br>
        </div>
    </div>
        
    <!-- Main page content -->
    <div class="row">
        <div class="col-12">
            <form id="main_form" name="main_form" method="POST" action="{% url 'add_recipe' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-md-3">
                        {{ recipe_form.title|as_crispy_field}}
                    </div>
                    <div class="col-12 col-md-9">
                        {{ recipe_form.intro|as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 col-md-3">
                        {{ recipe_form.prep_time|as_crispy_field}}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ recipe_form.cook_time|as_crispy_field}}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ recipe_form.total_time|as_crispy_field}}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ recipe_form.servings|as_crispy_field}}
                    </div>
                    <div class="col-12 col-md-3">
                        <p class="mb-2">Choose Image</p>
                        {{ recipe_form.image }}
                    </div>
                    <div class="col-12 col-md-9">
                        {{ recipe_form.image_credit | as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-6">
                        <div id="cat-height">
                            {{ recipe_form.category | as_crispy_field}}
                        </div>
                        {{ new_category_form|crispy }}
                    </div>
                    <div class="col-12 col-md-6">
                        <div id="tag-height">
                            {{ recipe_form.tag | as_crispy_field }}
                        </div>
                        {{ new_tag_form.tagname | as_crispy_field }}
                    </div>
                </div>

                <!-- Ingrdeients formset -->
                <p>Ingredients</p>
                {{ formset.management_form }}
                <div>
                    {% for form in formset %}
                    {{ form.id }}
                    <div class="row ingredients">
                        <div class="col-3 col-md-2">
                            {{ form.quantity|as_crispy_field }}
                        </div>
                        <div class="col-3 col-md-2">
                            {{ form.unit|as_crispy_field }}
                        </div>
                        <div class="col-6 col-md-4">
                            {{ form.preparation|as_crispy_field }}
                        </div>
                        <div class="col-12 col-md-4">
                            {{ form.name|as_crispy_field }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
                <div class="row more-ingredients-row">
                    <div class="col-12">
                        <button id="add-ingredient-form" class="btn btn-green mb-3">Add more ingredients</button>
                    </div>
                </div>
                <div class="row recipe-directions">
                    <div class="col-12">
                        {{ recipe_form.media}}
                        {{ recipe_form.directions|as_crispy_field}}
                    </div>
                </div>
                <label class="form-check-label" for="id-add-more-recipes">Add another recipe?</label>
                <input class="form-check-input ml-2 mr-0" type="checkbox" id="id-add-more-recipes" name="add-more-recipes">
                <div class="ckeditor-message">
                    Please add how to make your recipe in the box above!
                </div>
                <div class="text-right">
                    <a class="btn btn-red" href="">Cancel</a>
                    <button class="btn btn-green" type="submit">Add Recipe</button>
                </div>
            </form>
        </div>
    </div>       
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    {% include 'recipes/includes/checkbox_height.html' %}
    {% include 'recipes/includes/image_credit_add.html' %}
    {% include 'recipes/includes/new_ingredients_add.html' %}
    {% include 'recipes/includes/ckeditor_validation.html' %}
    <script>
        // Change color of checkbox. Works in Chrome and Safari desktop
        $('input[type="checkbox"]').css('filter', 'hue-rotate(300deg)');
    </script>
    <script>
        // Ensure ingredient fields are required
        $('input[name="ingredients-0-quantity"]').prop('required', true);
        $('input[name="ingredients-0-unit"]').prop('required', true);
        $('input[name="ingredients-0-name"]').prop('required', true);
    </script>
{% endblock %}

recipes/templates/recipes/create_recipe.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
{% endblock %}

{% block extra_title %}
 | Add a Recipe
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container content mb-2">
    <!-- Page title row -->
    <div class="row">
        <div class="col-12 mt-3">
            <h2 class="font-weight-bold">Add A New Recipe</h2>
            <br>
        </div>
    </div>
        
    <!-- Main page content -->
    <div class="row">
        <div class="col-12">
            <form id="main-form" method="POST" action="" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 col-md-3">
                        {{ recipe_form.title|as_crispy_field}}
                    </div>
                    <div class="col-12 col-md-9">
                        {{ recipe_form.intro|as_crispy_field}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 col-md-3">
                        {{ recipe_form.prep_time|as_crispy_field}}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ recipe_form.cook_time|as_crispy_field}}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ recipe_form.total_time|as_crispy_field}}
                    </div>
                    <div class="col-6 col-md-3">
                        {{ recipe_form.servings|as_crispy_field}}
                    </div>
                    <div class="col-12 col-md-3">
                        <p class="mb-2">Choose Image</p>
                        {{ recipe_form.image }}
                    </div>
                    <div class="col-12 col-md-9">
                        {{ recipe_form.image_credit | as_crispy_field }}
                    </div>
                    <div class="col-12 col-md-6">
                        {{ recipe_form.category | as_crispy_field }}
                        {{ new_category_form|crispy }}
                    </div>
                    <div class="col-12 col-md-6">
                        {{ recipe_form.tag | as_crispy_field }}
                        {{ new_tag_form.tagname | as_crispy_field }}
                    </div>
                </div>

                <p>Ingredients</p>
                {{ formset.management_form }}
                <div class="ingredient-form">
                    {% for form in formset %}
                    <div class="row ingredients">
                        <div class="col-3 col-md-2">
                            {{ form.quantity|as_crispy_field }}
                        </div>
                        <div class="col-3 col-md-2">
                            {{ form.unit|as_crispy_field }}
                        </div>
                        <div class="col-6 col-md-4">
                            {{ form.preparation|as_crispy_field }}
                        </div>
                        <div class="col-12 col-md-4">
                            {{ form.name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row delete-button">
                        <div class="col">
                            <p>{{ form.DELETE }} Delete</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
                <div class="row more-ingredients-row">
                    <div class="col-12">
                        <button id="add-button" class="btn btn-green mb-3">Add more ingredients</button>
                    </div>
                </div>
                <div class="row recipe-directions">
                    <div class="col-12">
                        {{ recipe_form.directions|as_crispy_field}}
                    </div>
                </div>
                <label class="form-check-label" for="id-add-more-recipes">Add another recipe?</label>
                <input class="form-check-input ml-2 mr-0" type="checkbox" id="id-add-more-recipes" name="add-more-recipes">
                <div class="text-right">
                    <a class="btn btn-red" href="">Cancel</a>
                    <button class="btn btn-green" type="submit">Add Recipe</button>
                </div>
            </form>
        </div>
    </div>       
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#div_id_image_credit').css('display', 'none');
        $('.btn-file').children('input').addClass('new-image');
        $('.new-image').change(function() {
            let file = $('.new-image')[0].files[0];
            $('#filename').text(`Image will be set to ${file.name}`);
            $('#div_id_image_credit').css('display', 'block');
            $('label[for="id_image_credit"]').text('Image Credit*');
            $('input[name="image_credit"]').prop('required', true);
        })
    </script>
    <script>
        let addButton = $('#add-button');
        let ingredients = $('.ingredients');
        let deleteButton = $('.delete-button')
        let count = 0;
        ingredients.slice(5).toggle();
        deleteButton.slice(5).toggle();
        addButton.on('click', function() {
            event.preventDefault();

            count++;
            if (count == 1) {
                ingredients.slice(5, 10).toggle();
                deleteButton.slice(5, 10).toggle();
            }
            if (count == 2) {
                ingredients.slice(10, 15).toggle();
                deleteButton.slice(10, 15).toggle();
            }
            if (count == 3) {
                ingredients.slice(15, 20).toggle();
                deleteButton.slice(15, 20).toggle();
            }
            if (count == 4) {
                ingredients.slice(20, 25).toggle();
                deleteButton.slice(20, 25).toggle();
                addButton.toggle();
            }
        })
    </script>
{% endblock %}